SELECT TOP (1000) [HospitalId]
      ,[HospitalName]
      ,[HospitalAddress]
      ,[HospitalPhoneNumber]
      ,[HospitalEmail]
      ,[TotalSlots]
      ,[SlotsAvailable]
      ,[RegisteredDate]
      ,[RemovedDate]
      ,[IsDeleted]
      ,[HospitalUid]
      ,[UpdatedDate]
      ,[HospitalPinCode]
  FROM [vaxtrack_sqlserver].[dbo].[Hospitals]