SELECT TOP (1000) [BookingId]
      ,[UserUid]
      ,[Dose1RequestedDateTime]
      ,[Dose1SlotNumber]
      ,[Dose1HospitalUid]
      ,[IsDose1Completed]
      ,[Dose1CompletedDateTime]
      ,[Dose2RequestedDateTime]
      ,[Dose2HospitalUid]
      ,[IsDose2Completed]
      ,[Dose2CompletedDateTime]
      ,[IsVaccinationCompleted]
      ,[VaccinationCompletedDateTime]
      ,[CreatedAt]
      ,[ModifiedAt]
      ,[IsD1RequestCanceled]
      ,[IsD2RequestCanceled]
      ,[IsDeleted]
  FROM [vaxtrack_sqlserver].[dbo].[Bookings]