SELECT TOP (1000) [UserId]
      ,[UserName]
      ,[UserBirthdate]
      ,[UserAge]
      ,[UserUid]
      ,[UserGender]
      ,[UserPhone]
      ,[UserRole]
      ,[ProfilePicturePath]
      ,[IsDeleted]
      ,[CreatedAt]
      ,[DeletedAt]
      ,[UpdatedAt]
      ,[UserAddress]
      ,[UserPinCode]
  FROM [vaxtrack_sqlserver].[dbo].[Users]